{
 "title": "Custom Exporter (External APIs)",
 "time": { "from": "2025-11-05T17:50:09.521Z", "to": "2025-11-05T17:53:55.296Z" },
 "panels": [
  {
   "title": "Time series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "# 8. Успешные API вызовы\r\nrate(successful_api_calls_total[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 9. Ошибочные API вызовы\r\nrate(failed_api_calls_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stat",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# 4. Курс EUR/USD\r\nexchange_usd_eur",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 5. Курс GBP/USD\r\nexchange_usd_gbp",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 6. Цена Bitcoin\r\ncrypto_btc_usd",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 7. Цена Ethereum\r\ncrypto_eth_usd",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# 1. Температура\r\nweather_temperature_celsius",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 2. Влажность\r\nweather_humidity_percent",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 3. Давление\r\nweather_pressure_hpa",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 10. UV Index\r\nweather_uv_index",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "# 1. Температура\r\nweather_temperature_celsius",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 2. Влажность\r\nweather_humidity_percent",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 3. Давление\r\nweather_pressure_hpa",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 4. Курс EUR/USD\r\nexchange_usd_eur",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 5. Курс GBP/USD\r\nexchange_usd_gbp",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 6. Цена Bitcoin\r\ncrypto_btc_usd",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 7. Цена Ethereum\r\ncrypto_eth_usd",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 8. Успешные API вызовы\r\nrate(successful_api_calls_total[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 9. Ошибочные API вызовы\r\nrate(failed_api_calls_total[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 10. UV Index\r\nweather_uv_index",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}