{
 "title": "Node Exporter Dashboard",
 "time": { "from": "2025-11-05T17:46:36.777Z", "to": "2025-11-05T17:51:38.985Z" },
 "panels": [
  {
   "title": "Bar chart",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "# 5. Load Average\r\nnode_load1",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 10. Running Processes\r\nnode_procs_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# 3. Memory Usage %\r\n(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 4. Disk Usage %\r\n(1 - (node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "# 2. CPU Usage %\r\n100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 6. Disk Read MB/s\r\nrate(node_disk_read_bytes_total[5m]) / 1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 7. Disk Write MB/s\r\nrate(node_disk_written_bytes_total[5m]) / 1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 8. Network Received MB/s\r\nrate(node_network_receive_bytes_total{device!=\"lo\"}[5m]) / 1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 9. Network Transmitted MB/s\r\nrate(node_network_transmit_bytes_total{device!=\"lo\"}[5m]) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 3. Memory Usage %\r\n(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 4. Disk Usage %\r\n(1 - (node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"})) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 5. Load Average\r\nnode_load1",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 6. Disk Read MB/s\r\nrate(node_disk_read_bytes_total[5m]) / 1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 7. Disk Write MB/s\r\nrate(node_disk_written_bytes_total[5m]) / 1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 8. Network Received MB/s\r\nrate(node_network_receive_bytes_total{device!=\"lo\"}[5m]) / 1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 9. Network Transmitted MB/s\r\nrate(node_network_transmit_bytes_total{device!=\"lo\"}[5m]) / 1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "# 10. Running Processes\r\nnode_procs_running",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}